# Generated by Django 3.1.12 on 2025-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='shoe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='shoe',
            table='shoe',
        ),
    ]
